### ISSUE TITLE
this doesn't work for me

### ISSUE THREAD

**Issue by ameliaWadd** [trestletech/ShinyDash-Sample#2]
The weather ap gives error:

Error in UseMethod("xmlRoot") : 
  no applicable method for 'xmlRoot' applied to an object of class "NULL"

**Comment by trestletech** [comment]
Hi. This app is pretty much deprecated by this point. I'd encourage you to check out https://rstudio.github.io/shinydashboard/ or http://rmarkdown.rstudio.com/flexdashboard/

**Comment by ameliaWadd** [comment]
Thanks, I use shinydashboard a lot already, it was specifically the weather widget I was interested in. Do you know of a working weather example?

**Comment by trestletech** [comment]
Oh, gotcha. Unfortunately I'm not aware of anything right now. Sorry!
